---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showroom-{{ .Values.terminal.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.terminal.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.terminal.name }}
    spec:
      # serviceAccountName: .Values.terminal.serviceAccount
      containers:
      - name: {{ .Values.terminal.name }}
        image: {{ .Values.terminal.image }}
        imagePullPolicy: Always
        args:
          - --base={{ .Values.terminal.wetty.base }}
          - --port={{ .Values.terminal.wetty.port }}
{{- if .Values.terminal.wetty.autoSshToBastion }}
          - --ssh-host={{ .Values.terminal.wetty.sshHost }}
          - --ssh-port={{ .Values.terminal.wetty.sshPort }}
          - --ssh-user={{ .Values.terminal.wetty.sshUser }}
          - --ssh-auth={{ .Values.terminal.wetty.sshAuth }}
          - --ssh-pass={{ .Values.terminal.wetty.sshPass }}
{{- end }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
          - name: terminal-secret
            mountPath: /sshkey/ # not implemented
        ports:
         - containerPort: {{ .Values.terminal.wetty.port }}
           protocol: TCP
        resources:
          {{- toYaml .Values.terminal.resources | nindent 10 }}
      volumes:
      - name: terminal-secret
        secret:
          secretName: terminal-secret
