---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.terminal.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.terminal.wetty.port }}
    protocol: TCP
    targetPort: {{ .Values.terminal.wetty.port }}
  selector:
    app.kubernetes.io/name: {{ .Values.terminal.name }}
