---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showroom-proxy
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: showroom-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: showroom-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: showroom-proxy
    spec:
      containers:
      - name: nginx
        image: {{ .Values.proxy.image }}
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-config
        - mountPath: /var/cache/nginx
          name: nginx-cache
        - mountPath: /var/run
          name: nginx-pid
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: web
          containerPort: 8080
      volumes:
      - configMap:
          defaultMode: 420
          name: showroom-proxy
        name: nginx-config
      - emptyDir: {}
        name: nginx-pid
      - emptyDir: {}
        name: nginx-cache
              #      securityContext:
              #        allowPrivilegeEscalation: true
              #        capabilities:
              #          drop: ["ALL"]
              #        securityContext:
              #          runAsNonRoot: false
              #        seccompProfile:
              #          type: RuntimeDefault
